"""GCT / Kronecker — la 7a arena indipendente del PvsNP-lab.

Coefficienti di Kronecker g(lam,mu,nu) di S_d ESATTI (Murnaghan-Nakayama, Fraction/int)
e il pattern di vanishing confrontato con le condizioni necessarie note (Dvir).

IPOTESI-LAB: su d<=5 il vanishing (g==0) COLLASSA nelle NC note.  KILLER:
sporadic_vanishing(d) non vuoto = vanishing sporadico = contenuto fuori dizionario.
Nessun claim su Kronecker positivity / GCT / P vs NP (vedi honesty boundary in kronecker.py).
"""

from .kronecker import (
    partitions,
    transpose,
    z_alpha,
    mn_character,
    hook_length_dimension,
    kronecker,
    nc_length,
    nc_maxpart,
    v_pred,
    vanishing_table,
    mismatches,
    sporadic_vanishing,
    nc_false_positive,
    honesty_note,
)
from .coverage import (
    is_two_row,
    is_two_column,
    is_hook,
    is_rectangle,
    special_shape,
    g_orbit,
    g_orbit_frozen,
    covered,
    covered_list,
    uncovered,
    coverage_summary,
)
from .saturation import (
    stretch,
    g_stretch,
    is_hole,
    perm_orbit,
    perm_key,
    shape_profile,
    classify,
    collisions,
    summary,
)
from .moment_cone import (
    max_parts,
    point,
    support_points,
    in_cone,
    is_deep_hole,
    holes,
    summary as cone_summary,
    facets,
    classify_facet,
    facet_report,
)
from .fast import (
    CharTable,
    character_table,
    g_fast,
    census,
)
from .beyond_wall import (
    _diagram_intersection,
    nc_dvir_full,
    nc_triangle,
    explained_zero,
    covered_ext,
    g_canonical,
    HuntResult,
    hunt,
    sanity_entry30,
    stretch_triple,
    stretch_witnesses,
    false_positives_dvir,
    false_positives_triangle,
    honesty_note as beyond_wall_honesty,
)
from .diagonal_census import (
    diagonal_zeros,
    classify_diag,
    stretch_diagonal,
    summary as diagonal_summary,
    STRETCH_MAX_D,
)
from .hook_depth import (
    hook_lam,
    g_hook_diag,
    hook_depth_row,
    summary as hook_depth_summary,
    HOOK_MAX_D,
)

__all__ = [
    "partitions",
    "transpose",
    "z_alpha",
    "mn_character",
    "hook_length_dimension",
    "kronecker",
    "nc_length",
    "nc_maxpart",
    "v_pred",
    "vanishing_table",
    "mismatches",
    "sporadic_vanishing",
    "nc_false_positive",
    "honesty_note",
    "is_two_row",
    "is_two_column",
    "is_hook",
    "is_rectangle",
    "special_shape",
    "g_orbit",
    "g_orbit_frozen",
    "covered",
    "covered_list",
    "uncovered",
    "coverage_summary",
    "stretch",
    "g_stretch",
    "is_hole",
    "perm_orbit",
    "perm_key",
    "shape_profile",
    "classify",
    "collisions",
    "summary",
    "max_parts",
    "point",
    "support_points",
    "in_cone",
    "is_deep_hole",
    "holes",
    "cone_summary",
    "facets",
    "classify_facet",
    "facet_report",
    "CharTable",
    "character_table",
    "g_fast",
    "census",
    "_diagram_intersection",
    "nc_dvir_full",
    "nc_triangle",
    "explained_zero",
    "covered_ext",
    "g_canonical",
    "HuntResult",
    "hunt",
    "sanity_entry30",
    "stretch_triple",
    "stretch_witnesses",
    "false_positives_dvir",
    "false_positives_triangle",
    "beyond_wall_honesty",
    "diagonal_zeros",
    "classify_diag",
    "stretch_diagonal",
    "diagonal_summary",
    "STRETCH_MAX_D",
    "hook_lam",
    "g_hook_diag",
    "hook_depth_row",
    "hook_depth_summary",
    "HOOK_MAX_D",
]
